const links = {
	// My Profiles
	LINKEDIN: "https://www.linkedin.com/in/louis-walter",
	GITHUB: "https://github.com/AFCMS",
	YOUTUBE: "https://www.youtube.com/@AFCMS",
	TWITCH: "https://www.twitch.tv/afcms",
	STEAM: "https://steamcommunity.com/id/AFCMS",
	NAMEMC: "https://namemc.com/profile/AFCMS.1",
	SPOTIFY: "https://open.spotify.com/user/7ysbf79u6lsoh7cg9j1jljiou",
	CONTENTDB: "https://content.luanti.org/users/AFCM",
	// Projects/Other
	ECOLEHEXAGONE: "https://www.ecole-hexagone.com",
	LUANTI: "https://www.luanti.org",
	VOXELIBRE: "https://content.luanti.org/packages/wuzzy/mineclone2",
	VITE: "https://vite.dev",
	REACT: "https://react.dev",
	PREACT: "https://preactjs.com",
	TAILWINDCSS: "https://tailwindcss.com",
	BOOTSTRAP: "https://getbootstrap.com",
	SUPABASE: "https://supabase.com",
	DJANGO: "https://www.djangoproject.com",
	FLASK: "https://flask.palletsprojects.com",
	GOLANG: "https://go.dev",
	SYMFONY: "https://symfony.com",
	DOCKER: "https://www.docker.com",
	KUBERNETES: "https://kubernetes.io",
	DISCORDJS: "https://discord.js.org",
	NODE: "https://nodejs.org",
	DENO: "https://deno.com",
	UNREAL: "https://www.unrealengine.com",
	BLENDER: "https://www.blender.org",
	DOTNET: "https://dotnet.microsoft.com",
	REDOT: "https://www.redotengine.org",
};

export default links;
