const links = {
	LINKEDIN: "https://www.linkedin.com/in/louis-walter",
	GITHUB: "https://github.com/AFCMS",
	CONTENTDB: "https://content.luanti.org/users/AFCM",
	ECOLEHEXAGONE: "https://www.ecole-hexagone.com",
	LUANTI: "https://www.luanti.org",
	VOXELIBRE: "https://content.luanti.org/packages/wuzzy/mineclone2",
	VITE: "https://vite.dev",
	REACT: "https://react.dev",
	PREACT: "https://preactjs.com",
	TAILWINDCSS: "https://tailwindcss.com",
	BOOTSTRAP: "https://getbootstrap.com",
	SUPABASE: "https://supabase.com",
	DJANGO: "https://www.djangoproject.com",
	FLASK: "https://flask.palletsprojects.com",
	GOLANG: "https://go.dev",
	SYMFONY: "https://symfony.com",
	DOCKER: "https://www.docker.com",
	KUBERNETES: "https://kubernetes.io",
	DISCORDJS: "https://discord.js.org",
	NODE: "https://nodejs.org",
	DENO: "https://deno.com",
};

export default links;
